[build]
  command = "npm run build"
  base = "helpless-halo/"
  publish = "dist"

[context.deploy-preview]
  publish = "dist/"

[functions]
  directory = "netlify/functions"

[[headers]]
  for = "/*"

  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"
    Feature-Policy = "geolocation 'self'; vibrate 'none'"
    Permissions-Policy = "geolocation=(self)"

# Remove or comment out CSP related headers if CSP is managed in astro.config.mjs
   Content-Security-Policy = "default-src 'self'; script-src 'self' 'nonce-gvsaDxhFfBoKoI01HTh7YA==' 'nonce-${nonce}' 'unsafe-inline'; style-src 'self' 'nonce-XYZ'"