[build]
command = "npm run build"
base = "helpless-halo/"
publish = "dist"

[build.environment]
SITE_URL = "https://www.musicstudio-ziebart.de"

[[headers]]
for = "/*"

[headers.values]
X-Frame-Options = "SAMEORIGIN"
X-XSS-Protection = "1; mode=block"
Access-Control-Allow-Origin = "*"
Vary = "Origin"
Timing-Allow-Origin = "https://www.musicstudio-ziebart.de"
Access-Control-Allow-Methods = "GET,POST,PUT,PATCH,DELETE"
Access-Control-Allow-Credentials = "true"
Access-Control-Allow-Crossorigin = "true"
X-Content-Type-Options = "nosniff"
